import os

WINDOW_WIDTH = 900
WINDOW_HEIGHT = 600

COLOR_WHITE = (255, 255, 255)

PLAYER_WIDTH = 80
PLAYER_HEIGHT = 80
PLAYER_VELOCITY = 20

BALL_SIZE = 20
BALL_VELOCITY_X = 20
BALL_VELOCITY_Y = 20


PATH_DIRECTORY = os.path.dirname(__file__)
PATH_DIRECTORY_IMAGES = os.path.join(PATH_DIRECTORY, 'images')
PATH_DIRECTORY_FONTS = os.path.join(PATH_DIRECTORY, 'fonts')
PATH_DIRECTORY_SOUNDS = os.path.join(PATH_DIRECTORY, 'sounds')
